package com.mycompany.librarymanagement;

public class AddBookWindow extends javax.swing.JDialog {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddBookWindow.class.getName());

    public AddBookWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    private Book resultBook = null;

    public Book getResultBook() {
        return resultBook;
    }

    public void setupForRegularBook() {
        this.setTitle("Add New Book");
        FORMAT.setVisible(false);
        SIZE.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
    }

    public void setupForEBook() {
        this.setTitle("Add New eBook");
    }
    public void setupForEdit(Book b) {
        this.setTitle("Edit Book");
        
        ISBN.setText(b.getIsbn());
        ISBN.setEditable(true); 
        TITLE.setText(b.getTitle());
        AUTHOR.setText(b.getAuthor());
        GENRE.setText(b.getGenre());
        YEAR.setText(String.valueOf(b.getYear()));
        
        if (b instanceof EBook) {
            EBook eb = (EBook) b; 
            
            FORMAT.setText(eb.getFileFormat());
            SIZE.setText(String.valueOf(eb.getFileSizeMB())); 
            
            FORMAT.setVisible(true);
            SIZE.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
        } else {
            FORMAT.setVisible(false);
            SIZE.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TITLE = new javax.swing.JTextField();
        AUTHOR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        GENRE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        YEAR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FORMAT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SIZE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ISBN = new javax.swing.JTextField();
        CANCEL = new javax.swing.JButton();
        ADD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Title");

        TITLE.addActionListener(this::TITLEActionPerformed);

        AUTHOR.addActionListener(this::AUTHORActionPerformed);

        jLabel3.setText("Author");

        GENRE.addActionListener(this::GENREActionPerformed);

        jLabel4.setText("Genre");

        YEAR.addActionListener(this::YEARActionPerformed);

        jLabel5.setText("Year");

        jLabel6.setText("Format");

        FORMAT.addActionListener(this::FORMATActionPerformed);

        jLabel7.setText("Size(MB)");

        SIZE.addActionListener(this::SIZEActionPerformed);

        jLabel8.setText("ISBN");

        ISBN.addActionListener(this::ISBNActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(FORMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YEAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(GENRE, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AUTHOR, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TITLE, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ISBN, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SIZE, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(AUTHOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(GENRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FORMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        CANCEL.setText("Cancel");
        CANCEL.addActionListener(this::CANCELActionPerformed);

        ADD.setBackground(new java.awt.Color(153, 153, 255));
        ADD.setText("Add");
        ADD.addActionListener(this::ADDActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CANCEL)
                    .addComponent(ADD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TITLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TITLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TITLEActionPerformed

    private void AUTHORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUTHORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AUTHORActionPerformed

    private void GENREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GENREActionPerformed

    private void YEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YEARActionPerformed

    private void FORMATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORMATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORMATActionPerformed

    private void SIZEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIZEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIZEActionPerformed

    private void ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        String isbnStr = ISBN.getText().trim();
        String titleStr = TITLE.getText().trim();
        String authorStr = AUTHOR.getText().trim();
        String genreStr = GENRE.getText().trim();
        String yearStr = YEAR.getText().trim();

        if (!isbnStr.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "ISBN must be a number!", "Invalid ISBN", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }

        if (titleStr.isEmpty() || authorStr.isEmpty() || genreStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Title, Author, and Genre cannot be empty!", "Missing Info", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int year;
        try {
            year = Integer.parseInt(yearStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Year must be a valid number!", "Invalid Year", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (SIZE.isVisible()) {
            String formatStr = FORMAT.getText().trim();
            String sizeStr = SIZE.getText().trim();

            if (formatStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Format cannot be empty for an eBook!", "Missing Info", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            double size;
            try {
                size = Double.parseDouble(sizeStr);
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Size (MB) must be a valid number!", "Invalid Size", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            resultBook = new EBook(isbnStr, titleStr, authorStr, genreStr, year, formatStr, size);
            
        } else {
            resultBook = new Book(isbnStr, titleStr, authorStr, genreStr, year);
        }
        this.dispose();
    }//GEN-LAST:event_ADDActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        this.dispose();
    }//GEN-LAST:event_CANCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddBookWindow dialog = new AddBookWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField AUTHOR;
    private javax.swing.JButton CANCEL;
    private javax.swing.JTextField FORMAT;
    private javax.swing.JTextField GENRE;
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField SIZE;
    private javax.swing.JTextField TITLE;
    private javax.swing.JTextField YEAR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
